let mock = [{
    id: 1,
    name: "Savage Love",
    artist: "Jason Derulo x Jawish 685",
    genre: "Pop",
    image: 'savage.png',
    FavStatus: '🤍',
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=Jvcv8trEuao'
  },
  {
    id: 2,
    name: "For The Night",
    artist: "Pop Smoke (feat. Lil Baby & DaBaby)",
    genre: "Rap",
    image: "night.png",
    FavStatus: '🤍',
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=Q9pjm4cNsfc'
  },
  {
    id: 3,
    name: "positions",
    artist: "Ariana Grande",
    genre: "Pop",
    image: 'ari.png',
    FavStatus: '🤍',
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=tcYodQoapMg'
  },
  {
    id: 4,
    name: "Golden",
    artist: "Harry Styles",
    genre: "Pop",
    image: 'golden.png',
    FavStatus: '🤍',
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=P3cffdsEXXw'
  },
  {
    id: 5,
    name: "WAP",
    artist: "Cardi B & Megan Thee Stallion",
    genre: "Rap",
    image: 'wap.png',
    FavStatus: '🤍',
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=Wc5IbN4xw70'
  },
  {
    id: 6,
    name: "Don't Need Friends",
    artist: "NAV (feat. Lil Baby)",
    genre: "Rap",
    image: 'nav.png',
    FavStatus: '🤍',
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=LEhVIjBOjrA'
  },
  {
    id: 7,
    name: "Forever After All",
    FavStatus: '🤍',
    artist: "Luke Combs",
    genre: "Country",
    image: 'luke.png',
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=fmbLCMGtEQc'
  },
  {
    id: 8,
    name: "Hawai (Remix)",
    FavStatus: '🤍',
    artist: "Maluma and The Weekend",
    genre: "Pop",
    image: 'hawai.png',
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=91vECNhvmMY'
  },
  {
    id: 9,
    name: "34+35",
    FavStatus: '🤍',
    artist: "Ariana Grande",
    genre: "Pop",
    image: 'ari.png',
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=cnyCcF20pRo',
  },
  {
    id: 10,
    name: "Laugh Now Cry Later",
    FavStatus: '🤍',
    artist: "Drake",
    genre: "Rap",
    image: 'drake.png',
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=JFm7YDVlqnI',
  },
  {
    id: 11,
    name: "Lonely",
    artist: "Justin Bieber & benny blanco",
    FavStatus: '🤍',
    genre: "Pop",
    image: "lonely.png",
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=xQOO2xGQ1Pc',
  },
  {
    id: 12,
    name: "Blinding Lights",
    FavStatus: '🤍',
    artist: "The Weeknd",
    genre: "R&B/Soul",
    image: "blinding.png",
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=4NRXx6U8ABQ',
  },
  {
    id: 13,
    name: "you broke me first",
    FavStatus: '🤍',
    artist: "tate McRae",
    genre: "Pop",
    image: "tate.png",
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=AG-erEMhumc',
  },
  {
    id: 14,
    name: "Dynamite",
    FavStatus: '🤍',
    artist: "BTS",
    genre: "K-Pop",
    image: "dynamite.png",
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=gdZLi9oWNZg'
  },
  {
    id: 15,
    name: "Lemonade",
    FavStatus: '🤍',
    artist: "Internet Money & Gunna (feat. Don Toliver & NAV)",
    genre: "Rap",
    image: "lemon.png",
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=U-fcXjcJXks'
  },
  {
    id: 16,
    name: "Levitating ",
    FavStatus: '🤍',
    artist: "Dua Lipa (feat DaBaby)",
    genre: "Pop",
    image: "lev.png",
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=TUVcZfQe-Kw'
  },
  {
    id: 17,
    name: "Be Like That",
    FavStatus: '🤍',
    artist: "Kane Brown, Swae Lee, Khalid",
    genre: "Pop",
    image: "belikethat.png",
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=GEAy7eXb2lo',
  },
  {
    id: 18,
    name: "Wonder",
    FavStatus: '🤍',
    artist: "Shawn Mendes",
    genre: "Pop",
    image: "wonder.png",
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=fHeQemJJQII'

  },
  {
    id: 19,
    name: "Take You Dancing",
    FavStatus: '🤍',
    artist: "Jason Derulo",
    genre: "Pop",
    image: "dancing.png",
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=s0-f5RncxcA'
  },
  {
    id: 20,
    name: "Holy",
    FavStatus: '🤍',
    artist: "Justin Bieber (feat. Chance the Rapper)",
    genre: "Pop",
    image: "holy.png",
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=pvPsJFRGleA'
},
  {
    id: 21,
    name: "Watermelon Sugar",
    FavStatus: '🤍',
    artist: "Harry Styles",
    genre: "Pop",
    image: "golden.png",
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=E07s5ZYygMg'
},
  {
    id: 22,
    name: "Circles",
    FavStatus: '🤍',
    artist: "Post Malone",
    genre: "Pop",
    image: "circles.png",
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=wXhTHyIgQ_U'
},
  {
    id: 23,
    name: "Whats Poppin",
    FavStatus: '🤍',
    artist: "Jack Harlow",
    genre: "Rap",
    image: "jack.png",
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=HIwAI05Y1fU'
},
  {
    id: 24,
    name: "King & Queens",
    FavStatus: '🤍',
    artist: "Ava Max",
    genre: "Pop",
    image: "king.png",
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=jH1RNk8954Q'
},
  {
    id: 25,
    name: "ily",
    FavStatus: '🤍',
    artist: "Surf Mesa",
    genre: "Pop",
    image: "ily.png",
    inCart: false,
    youtube: 'https://www.youtube.com/watch?v=89degLrNZM8'
},
]

export default mock;
